/// >>>  I use this GUI frame for Test the Main frame  <<<<
/// >>>  This class will be replaced whit the real GUI class ,  <<<<<<<<<  

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package NewsAndInformationHUB;

/**
 *
 * @author arets
 */
public class CalculatorGUI extends javax.swing.JInternalFrame {

    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculatorLBL = new javax.swing.JLabel();
        day1LBL = new javax.swing.JLabel();
        day2LBL = new javax.swing.JLabel();
        day3LBL = new javax.swing.JLabel();
        day4LBL = new javax.swing.JLabel();
        day5LBL = new javax.swing.JLabel();
        day19LBL = new javax.swing.JLabel();
        day20LBL = new javax.swing.JLabel();
        day21LBL = new javax.swing.JLabel();
        day22LBL = new javax.swing.JLabel();
        day23LBL = new javax.swing.JLabel();
        day24LBL = new javax.swing.JLabel();
        day27LBL = new javax.swing.JLabel();
        day30LBL = new javax.swing.JLabel();
        day31LBL = new javax.swing.JLabel();
        day25LBL = new javax.swing.JLabel();
        day26LBL = new javax.swing.JLabel();
        day6LBL = new javax.swing.JLabel();
        day7LBL = new javax.swing.JLabel();
        day8LBL = new javax.swing.JLabel();
        day9LBL = new javax.swing.JLabel();
        day10LBL = new javax.swing.JLabel();
        day11LBL = new javax.swing.JLabel();
        day12LBL = new javax.swing.JLabel();
        day13LBL = new javax.swing.JLabel();
        day14LBL = new javax.swing.JLabel();
        day15LBL = new javax.swing.JLabel();
        day17LBL = new javax.swing.JLabel();
        day18LBL = new javax.swing.JLabel();
        day16LBL = new javax.swing.JLabel();
        day29LBL = new javax.swing.JLabel();
        day28LBL = new javax.swing.JLabel();
        day1TF = new javax.swing.JTextField();
        day8TF = new javax.swing.JTextField();
        day10TF = new javax.swing.JTextField();
        day9TF = new javax.swing.JTextField();
        day11TF = new javax.swing.JTextField();
        day12TF = new javax.swing.JTextField();
        day13TF = new javax.swing.JTextField();
        day14TF = new javax.swing.JTextField();
        day15TF = new javax.swing.JTextField();
        day4TF = new javax.swing.JTextField();
        day5TF = new javax.swing.JTextField();
        day7TF = new javax.swing.JTextField();
        day6TF = new javax.swing.JTextField();
        day2TF = new javax.swing.JTextField();
        day3TF = new javax.swing.JTextField();
        day20TF = new javax.swing.JTextField();
        day19TF = new javax.swing.JTextField();
        day18TF = new javax.swing.JTextField();
        day21TF = new javax.swing.JTextField();
        day22TF = new javax.swing.JTextField();
        day24TF = new javax.swing.JTextField();
        day25TF = new javax.swing.JTextField();
        day26TF = new javax.swing.JTextField();
        day27TF = new javax.swing.JTextField();
        day28TF = new javax.swing.JTextField();
        day29TF = new javax.swing.JTextField();
        day30TF = new javax.swing.JTextField();
        day16TF = new javax.swing.JTextField();
        day17TF = new javax.swing.JTextField();
        day23TF = new javax.swing.JTextField();
        day31TF = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 540));

        calculatorLBL.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        calculatorLBL.setText("CalculatorGUI Form / It is not connected");

        day1LBL.setText("Day 1 :");

        day2LBL.setText("Day 2 :");

        day3LBL.setText("Day 3 :");

        day4LBL.setText("Day 4 :");

        day5LBL.setText("Day 5 :");

        day19LBL.setText("Day 19 :");

        day20LBL.setText("Day 20 :");

        day21LBL.setText("Day 21:");

        day22LBL.setText("Day 22 :");

        day23LBL.setText("Day 23 : ");

        day24LBL.setText("Day 24 :");

        day27LBL.setText("Day 27 :");

        day30LBL.setText("Day 30 :");

        day31LBL.setText("Day 31 :");

        day25LBL.setText("Day 25 :");

        day26LBL.setText("Day 26 :");

        day6LBL.setText("Day 6 :");

        day7LBL.setText("Day 7 :");

        day8LBL.setText("Day 8 :");

        day9LBL.setText("Day 9 :");

        day10LBL.setText("Day 10 :");

        day11LBL.setText("Day 11 :");

        day12LBL.setText("Day 12 :");

        day13LBL.setText("Day 13 :");

        day14LBL.setText("Day 14 :");

        day15LBL.setText("Day 15 :");

        day17LBL.setText("Day 17 :");

        day18LBL.setText("Day 18 :");

        day16LBL.setText("Day 16 :");

        day29LBL.setText("Day 29 :");

        day28LBL.setText("Day 28 :");

        displayTA.setColumns(20);
        displayTA.setRows(5);
        jScrollPane2.setViewportView(displayTA);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setText("Calculate");

        exitBTN.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitBTN)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day13LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day13TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day12LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day12TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day11LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day11TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day5LBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(day5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day4LBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(day4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day3LBL)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(day3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day10LBL)
                                            .addComponent(day9LBL)
                                            .addComponent(day8LBL)
                                            .addComponent(day7LBL)
                                            .addComponent(day6LBL))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day6TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day7TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day8TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day9TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day10TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day1LBL)
                                            .addComponent(day2LBL))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(day19LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day19TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day20LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day20TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day22LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day22TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(day21LBL)
                                                .addGap(21, 21, 21)
                                                .addComponent(day21TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day26LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day26TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day25LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day25TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(day18LBL)
                                                    .addComponent(day17LBL))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(day18TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(day17TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day16LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day16TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day14LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day14TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(day15LBL)
                                                .addGap(18, 18, 18)
                                                .addComponent(day15TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(day24LBL)
                                            .addComponent(day23LBL))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(day24TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(day23TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day27LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day27TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day31LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day31TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day30LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day30TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day29LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day29TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(day28LBL)
                                        .addGap(18, 18, 18)
                                        .addComponent(day28TF, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(calculatorLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calculatorLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day1LBL)
                    .addComponent(day1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day27LBL)
                    .addComponent(day27TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day14LBL)
                    .addComponent(day14TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day2LBL)
                    .addComponent(day2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day28LBL)
                    .addComponent(day28TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day15LBL)
                    .addComponent(day15TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day3LBL)
                    .addComponent(day3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day29LBL)
                    .addComponent(day29TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day16LBL)
                    .addComponent(day16TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day4LBL)
                    .addComponent(day4TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day30LBL)
                    .addComponent(day30TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day17LBL)
                    .addComponent(day17TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day5LBL)
                    .addComponent(day5TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day31LBL)
                    .addComponent(day31TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day18LBL)
                    .addComponent(day18TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day6LBL)
                    .addComponent(day6TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day19LBL)
                    .addComponent(day19TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day7LBL)
                            .addComponent(day7TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day20LBL)
                            .addComponent(day20TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day8LBL)
                            .addComponent(day8TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day21LBL)
                            .addComponent(day21TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day9LBL)
                            .addComponent(day9TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day22LBL)
                            .addComponent(day22TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day10LBL)
                            .addComponent(day10TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day23LBL)
                            .addComponent(day23TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(day11LBL)
                    .addComponent(day11TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day24LBL)
                    .addComponent(day24TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day12LBL)
                            .addComponent(day12TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day25LBL)
                            .addComponent(day25TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(day13LBL)
                            .addComponent(day13TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(day26LBL)
                            .addComponent(day26TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(exitBTN)))
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculatorLBL;
    private javax.swing.JLabel day10LBL;
    private javax.swing.JTextField day10TF;
    private javax.swing.JLabel day11LBL;
    private javax.swing.JTextField day11TF;
    private javax.swing.JLabel day12LBL;
    private javax.swing.JTextField day12TF;
    private javax.swing.JLabel day13LBL;
    private javax.swing.JTextField day13TF;
    private javax.swing.JLabel day14LBL;
    private javax.swing.JTextField day14TF;
    private javax.swing.JLabel day15LBL;
    private javax.swing.JTextField day15TF;
    private javax.swing.JLabel day16LBL;
    private javax.swing.JTextField day16TF;
    private javax.swing.JLabel day17LBL;
    private javax.swing.JTextField day17TF;
    private javax.swing.JLabel day18LBL;
    private javax.swing.JTextField day18TF;
    private javax.swing.JLabel day19LBL;
    private javax.swing.JTextField day19TF;
    private javax.swing.JLabel day1LBL;
    private javax.swing.JTextField day1TF;
    private javax.swing.JLabel day20LBL;
    private javax.swing.JTextField day20TF;
    private javax.swing.JLabel day21LBL;
    private javax.swing.JTextField day21TF;
    private javax.swing.JLabel day22LBL;
    private javax.swing.JTextField day22TF;
    private javax.swing.JLabel day23LBL;
    private javax.swing.JTextField day23TF;
    private javax.swing.JLabel day24LBL;
    private javax.swing.JTextField day24TF;
    private javax.swing.JLabel day25LBL;
    private javax.swing.JTextField day25TF;
    private javax.swing.JLabel day26LBL;
    private javax.swing.JTextField day26TF;
    private javax.swing.JLabel day27LBL;
    private javax.swing.JTextField day27TF;
    private javax.swing.JLabel day28LBL;
    private javax.swing.JTextField day28TF;
    private javax.swing.JLabel day29LBL;
    private javax.swing.JTextField day29TF;
    private javax.swing.JLabel day2LBL;
    private javax.swing.JTextField day2TF;
    private javax.swing.JLabel day30LBL;
    private javax.swing.JTextField day30TF;
    private javax.swing.JLabel day31LBL;
    private javax.swing.JTextField day31TF;
    private javax.swing.JLabel day3LBL;
    private javax.swing.JTextField day3TF;
    private javax.swing.JLabel day4LBL;
    private javax.swing.JTextField day4TF;
    private javax.swing.JLabel day5LBL;
    private javax.swing.JTextField day5TF;
    private javax.swing.JLabel day6LBL;
    private javax.swing.JTextField day6TF;
    private javax.swing.JLabel day7LBL;
    private javax.swing.JTextField day7TF;
    private javax.swing.JLabel day8LBL;
    private javax.swing.JTextField day8TF;
    private javax.swing.JLabel day9LBL;
    private javax.swing.JTextField day9TF;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
