/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NewsAndInformationHUB;

import java.awt.BorderLayout;
import java.awt.Desktop;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

public class NewsFeedGUI extends javax.swing.JInternalFrame {
    private JTabbedPane mainFrame;
    private JList<String> articleJL; // Displaying articles
    private NewsFeed newsFeed;

    /**
     * Creates new form NewsFeedGUI
     */
    public NewsFeedGUI() {
        this.newsFeed = new NewsFeed(); // Initialize newsFeed with sample data
        initComponents();
        setupTabs();
        refreshContent();
    }

    // Constructor with a NewsFeed object.
    public NewsFeedGUI(NewsFeed newsFeed) {
        this.newsFeed = newsFeed;
        initComponents();
        setupTabs();
        refreshContent();
    }

    private void setupTabs() {
        mainFrame = new JTabbedPane(); // Create a tabbed pane

         // Initialize JLists for articles, videos, and research
        articleJL = new JList<>();
        videoJL = new JList<>();
      //researchJL = new JList<>();

        // Add each JList in a JScrollPane directly to mainFrame only once
        mainFrame.addTab("Article List", new JScrollPane(articleJL));
        mainFrame.addTab("Video List", new JScrollPane(videoJL));
      //mainFrame.addTab("Research List", new JScrollPane(researchJL));

        // Set layout and add main frame to GUI
        setLayout(new BorderLayout());
        add(mainFrame, BorderLayout.CENTER);
    }

    
    
    // Displays articles in the article list.
    public void displayArticles(List<String> articles) {
        articleJL.setListData(articles.toArray(new String[0])); // Populate the article list
    }
    
    // Displays Video in the article list.
    public void displayVideos(List<String> videos) {
        videoJL.setListData(videos.toArray(new String[0])); // Populate the video list
    }
    
   // In the progress  
   // Displays research in the article list.
   // public void displayResearch(List<String> research) {
   //     researchJL.setListData(research.toArray(new String[0])); // Populate the research list
   // }

    // efreshes the content in all tabs by fetching data from NewsFeed.
    public void refreshContent() {
    List<Article> articles = newsFeed.getLatestArticles();
    List<String> articleTitles = new ArrayList<>();
    for (Article article : articles) {
        articleTitles.add(article.getTitle()); // Use article titles for display
    }
    displayArticles(articleTitles);

    List<Video> videos = newsFeed.getLatestVideos();
    List<String> shortTitles = new ArrayList<>();
    for (Video video : videos) {
        shortTitles.add(video.getTitle());  // Add video titles to the display list
    }
    displayVideos(shortTitles);
  
   // Fetch and display research papers
   // List<String> research = newsFeed.getLatestResearch();
   // displayResearch(research);

    // Add a mouse listener to open URLs for videos
    videoJL.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int index = videoJL.locationToIndex(evt.getPoint());
            if (index >= 0 && index < videos.size()) {
                Video selectedVideo = videos.get(index);
                openLinkInBrowser(selectedVideo.getUrl());
            }
        }
    });

    // Add a mouse listener to open URLs for articles
    articleJL.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int index = articleJL.locationToIndex(evt.getPoint());
            if (index >= 0 && index < articles.size()) {
                Article selectedArticle = articles.get(index);
                openLinkInBrowser(selectedArticle.getUrl());  // Open article link in the browser
            }
        }
    });
    }
    
    //  Opens a URL in the default web browser.
    private void openLinkInBrowser(String url) {
    try {
        Desktop desktop = Desktop.getDesktop();
        desktop.browse(new URI(url)); // Open the given URL
    } catch (Exception e) {
        e.printStackTrace(); // Print error details if the URL can't be opened
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainFrame = new javax.swing.JTabbedPane();
        videoListTab = new javax.swing.JTabbedPane();
        ScrollPane1 = new javax.swing.JScrollPane();
        videoJL = new javax.swing.JList<>();
        researchListTab = new javax.swing.JTabbedPane();
        ScrollPane2 = new javax.swing.JScrollPane();
        researchJL = new javax.swing.JList<>();
        articleListTab = new javax.swing.JTabbedPane();
        ScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 540));

        jPanel1.setPreferredSize(new java.awt.Dimension(840, 540));

        ScrollPane1.setViewportView(videoJL);

        videoListTab.addTab("tab1", ScrollPane1);

        MainFrame.addTab("VideoList", videoListTab);

        ScrollPane2.setViewportView(researchJL);

        researchListTab.addTab("tab1", ScrollPane2);

        MainFrame.addTab("ResearchList", researchListTab);

        ScrollPane3.setViewportView(jList1);

        articleListTab.addTab("tab1", ScrollPane3);

        MainFrame.addTab("ArticleList", articleListTab);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(MainFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewsFeedGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewsFeed newsFeed = new NewsFeed();  // Create a NewsFeed object
                new NewsFeedGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainFrame;
    private javax.swing.JScrollPane ScrollPane1;
    private javax.swing.JScrollPane ScrollPane2;
    private javax.swing.JScrollPane ScrollPane3;
    private javax.swing.JTabbedPane articleListTab;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList<String> researchJL;
    private javax.swing.JTabbedPane researchListTab;
    private javax.swing.JList<String> videoJL;
    private javax.swing.JTabbedPane videoListTab;
    // End of variables declaration//GEN-END:variables
}
